version: '3.1'

services:

  db:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: qwerty
      POSTGRES_PASSWORD: 12345
    volumes:
      - ./data:/var/lib/postgresql
    ports:
      - '5432:5432'
